# -*- coding: utf-8 -*-
"""project Final version heart_disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zs0zXVxbvWzTiARS8tQTioG2HfVFB8qU
"""

# Step 1: Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

# Step 2: Load the Dataset

df = pd.read_csv('/content/drive/MyDrive/project Final version /Heart disease data.csv')

# Step 3: Display basic info
print("Dataset Shape:", df.shape)
df.head()

# Step 4: Exploratory Data Analysis (EDA)
plt.figure(figsize=(6, 4))
sns.countplot(x='target', data=df, palette={'0': 'lightgreen', '1': 'lightblue'})
plt.title("Target Variable Distribution (0 = No Disease, 1 = Disease)")
plt.show()

# Step 5: Data Preprocessing
# Check for missing values
print("Missing values:\n", df.isnull().sum())

# Correlation heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Step 5: Value Counts for Categorical Columns
# categorical_cols = ['Sex', 'Diabetes', 'Family History', 'Smoking',
#                     'Obesity', 'Previous Heart Problems', 'Medication Use']

# for col in categorical_cols:
#     print(f"\nValue Counts for {col}:\n")
#     print(df[col].value_counts())

# Step 6: Bivariate Analysis - Categorical vs Target
# for col in categorical_cols:
#     plt.figure(figsize=(6,4))
#     sns.countplot(x=col, hue='Heart Attack Risk', data=df)
#     plt.title(f'{col} vs Heart Disease')
#     plt.show()

# Feature scaling
X = df.drop('target', axis=1)
y = df['target']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 6: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 7: Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Machine": SVC(probability=True),
    "Random Forest": RandomForestClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Step 8: Train and evaluate models
results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    results[name] = [acc, prec, rec, f1]

    print(f"\nModel: {name}")
    print("Classification Report:\n", classification_report(y_test, y_pred))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f"{name} - Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

# Step 9: Compare model performance
results_df = pd.DataFrame(results, index=['Accuracy', 'Precision', 'Recall', 'F1-Score']).T
print("\nModel Performance Comparison:")
display(results_df)

"""**From the above results, Support Vector Machine (SVM) is the best model**"""

# Visualization of results
results_df.plot(kind='bar', figsize=(12, 6))
plt.title("Model Performance Metrics")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.ylim(0, 1.1)
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""** Basic Python Console Input:**"""

!pip install gradio

"""**Web Interface with Gradio (Interactive App)**"""

# Step 1: Imports
import pandas as pd
import numpy as np
import gradio as gr

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC



# Step 3: Preprocessing
X = df.drop('target', axis=1)
y = df['target']

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 4: Train SVM Model
svm_model = SVC(probability=True)
svm_model.fit(X_train, y_train)

# Step 5: Define prediction function
def predict_heart_attack(
    age,	gender,	chestpain,	restingBP,	serumcholestrol,	fastingbloodsugar,
    restingrelectro,	maxheartrate,	exerciseangia,	oldpeak,	slope,	noofmajorvessels

):



    # Create a DataFrame from input
    input_data = pd.DataFrame([[
        age,	gender,	chestpain,	restingBP,	serumcholestrol,	fastingbloodsugar,
        restingrelectro,	maxheartrate,	exerciseangia,	oldpeak,	slope,	noofmajorvessels

    ]], columns=[
        'age', 'gender', 'chestpain', 'restingBP', 'serumcholestrol',
        'fastingbloodsugar', 'restingrelectro', 'maxheartrate',
        'exerciseangia', 'oldpeak', 'slope', 'noofmajorvessels'
    ])

    # Apply the same scaling
    input_scaled = scaler.transform(input_data)

    # Make prediction
    prediction = svm_model.predict(input_scaled)[0]
    proba = svm_model.predict_proba(input_scaled)[0][1]






    result = "High Risk of Heart Attack" if prediction == 1 else "Low Risk of Heart Attack"
    return f"{result} (Confidence: {proba:.2f})"

# Step 6: Define Gradio Interface
inputs = [
    gr.Number(label="Age"),
    gr.Dropdown([0, 1], label="Gender (0 = Female, 1 = Male)"),
    gr.Dropdown([0, 1, 2, 3], label="Chestpain (0 = typical angina, 1 = atypical angina, 2=non-anginal pain, 3= asymptomatic )"),
    gr.Number(label="RestingBP"),
    gr.Number(label="Serumcholestrol"),
    gr.Dropdown([0, 1], label="Fasting blood sugar, 0,1 > 120 mg/dl. (0 = false , 1 = true) "),
    gr.Dropdown([0, 1, 2], label="Resting electrocardiogram results (0 = normal, 1 = ST-T wave abnormality, 2=left ventricular hypertrophy )"),
    gr.Number(label="Maximum heart rate achieved"),
    gr.Dropdown([0, 1], label="Exercise induced angina (0 = No, 1 = yes)"),
    gr.Number(label="oldpeak"),
    gr.Dropdown([1, 2, 3], label="Slope of the peak exercise ST segment (1 = upsloping, 2 = flat, 3=downsloping )"),




    gr.Dropdown([0, 1, 2, 3], label="Number of major vessels"),


]

gr.Interface(
    fn=predict_heart_attack,
    inputs=inputs,
    outputs=gr.Textbox(label="Heart Attack Risk Prediction"),
    title="Heart Attack Risk Predictor (SVM)",
    description="Enter patient data to predict the risk of heart attack."
).launch()